### ISSUE TITLE
Change the context in client function.

### ISSUE THREAD

**Issue by fcavani** [stacktic/dropbox#18]
Hi, I need to change the context from the default (oauth2.NoContext) to a custom context like this:
```
ctx := context.WithValue(oauth2.NoContext, oauth2.HTTPClient, &http.Client{
		Transport: &http.Transport{
			DisableKeepAlives:     false,
			Dial:                  dialTimeout,
			TLSHandshakeTimeout:   60 * time.Second,
			ResponseHeaderTimeout: 60 * time.Second,
		},
		Timeout: 60 * time.Second,
	})
```
Can you (or I make a patch) insert in somewhere a way to do it?
Tanks.

**Comment by stacktic** [comment]
Hi,
You can do this with the pull request I merged from @meshelton (#17 4f7d6e9).
