### ISSUE TITLE
Change size of file to int64

### ISSUE THREAD

**Issue by ncw** [stacktic/dropbox#19]
One of my users (see ncw/rclone#80) has been getting this error on large files `Couldn't list: json: cannot unmarshal number 5099896832 into Go value of type int`.

This is because he has a file of > 2GB whose size won't unmarshal into an `int`.

In `dropbox.go` it looks like the below should be an int64 instead of an int.

```go
type Entry struct {
    Bytes                int       `json:"bytes,omitempty"`        // Size of the file in bytes.
```

What I'd like to do is change `Bytes` to be an `int64`.  This would be a breaking API change, but one that is easy to fix for the users of this package I think.

I'm happy to submit a PR if you agree, or work on some alternative plan if you don't!

Thanks

Nick

**Comment by stacktic** [comment]
Hi Nick,

Thank you for reporting this.
I would happily accept a PR fixing this in the Entry struct and in the ChunkUploadResponse struct in which the same problem is present for the Offset field.

Thanks,

Arnaud
